#ifndef _DIO_CONFIG_H_
#define _DIO_CONFIG_H_

#define DIO_PORTA_PIN0_DIR OUTPUT
#define DIO_PORTA_PIN1_DIR OUTPUT
#define DIO_PORTA_PIN2_DIR OUTPUT
#define DIO_PORTA_PIN3_DIR INPUT
#define DIO_PORTA_PIN4_DIR INPUT
#define DIO_PORTA_PIN5_DIR OUTPUT
#define DIO_PORTA_PIN6_DIR OUTPUT
#define DIO_PORTA_PIN7_DIR OUTPUT

#define DIO_PORTB_PIN0_DIR OUTPUT
#define DIO_PORTB_PIN1_DIR OUTPUT
#define DIO_PORTB_PIN2_DIR OUTPUT
#define DIO_PORTB_PIN3_DIR INPUT
#define DIO_PORTB_PIN4_DIR INPUT
#define DIO_PORTB_PIN5_DIR OUTPUT
#define DIO_PORTB_PIN6_DIR OUTPUT
#define DIO_PORTB_PIN7_DIR OUTPUT

#endif