/* Options: EXTI_ENABLE, EXTI_DISABLE */
#define EXTI_INT0_STATUS    EXTI_ENABLE
#define EXTI_INT1_STATUS    EXTI_DISABLE
#define EXTI_INT2_STATUS    EXTI_DISABLE

/* Options: EXTI_FALLING_EDGE, EXTI_RISING_EDGE, EXTI_LOW_LEVEL, EXTI_ANY_LOGICAL_CHANGE */
#define EXTI_INT0_TRIGGER   EXTI_FALLING_EDGE